create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  rating text not null check (rating in ('helpful', 'unhelpful')),
  question text not null,
  answer text not null,
  conversation jsonb not null default '[]'::jsonb,
  user_agent text,
  ip_address text,
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;
